<?php

$CONFIG = [
    'has_internet_connection'       => false,
    'updatechecker'                 => false,
    'knowledgebaseenabled'          => false,
    'appstoreenabled'               => false,
    'theme'                         => 'karsaaz',
    'reference_opengraph'           => false,
    'connectivity_check_domains'    => [],
    'allow_local_remote_servers'    => true,
    'productName'                   => 'Karsaaz Cloud',
    'defaultapp'                    => 'dashboard,files',
    'default_language'              => 'en',
    'default_locale'                => 'en_US',
    'default_timezone'              => 'Asia/Karachi',
    'default_phone_region'          => 'PK',
    'trusted_domains'               => [
        0 => 'localhost',
        1 => '192.168.18.97',
        2 => '192.168.18.61',
        3 => '127.0.0.1',
        4 => '192.168.100.25',
        5 => '192.168.18.118',
        6 => '0.0.0.0',
        7 => '192.168.18.78',
    ],
    
    'mail_from_address'             => 'tameem.karsaaz',
    'mail_domain'                   => 'gmail.com',
    'mail_smtpmode'                 => 'smtp',
    'mail_sendmailmode'             => 'smtp',
    'mail_smtphost'                 => 'smtp.gmail.com',
    'mail_smtpport'                 => 587,
    'mail_smtpsecure'               => 'tls',
    'mail_smtpauth'                 => true,
    'mail_smtpauthtype'             => 'LOGIN',
    'mail_smtpname'                 => 'tameem.karsaaz@gmail.com',
    'mail_smtppassword'             => getenv('MAIL_SMTP_PASSWORD') ?: '',
    'mail_smtptimeout'              => 30,
];
