/*
 * SPDX-FileCopyrightText: 2026 Karsaaz
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

export const theme = {
  colors: {
    background: "#f8fafc",
    surface: "#ffffff",
    surfaceMuted: "#f1f5f9",
    text: "#0f172a",
    textDark: "#020617",
    textSecondary: "#475569",
    textMuted: "#64748b",
    textSubtle: "#94a3b8",
    border: "#e2e8f0",
    borderLight: "#e2e8f0",
    inputBg: "#f8fafc",
    infoBg: "#eff6ff",
    accent: "#1e3a8a",
    accentBright: "#3b82f6",
    link: "#2563eb",
    success: "#10b981",
    successBright: "#34d399",
    gradientStart: "#3b82f6",
    gradientEnd: "#1e3a8a",
    tabBar: "#0f172a",
    tabBarActive: "#ffffff",
    tabBarInactive: "rgba(148,163,184,0.6)",
    storageImages: "#10b981",
    storageDocs: "#3b82f6",
    storageVideos: "#f59e0b",
    storageOther: "#d946ef",
    storageEmpty: "#cbd5e1",
    folderOrangeStart: "#f59e0b",
    folderOrangeEnd: "#ea580c",
  },
  radius: {
    sm: 6,
    md: 12,
    lg: 16,
    xl: 24,
    pill: 999,
  },
  spacing: {
    screen: 24,
    card: 16,
    gap: 8,
  },
  typography: {
    hero: { fontSize: 30, lineHeight: 36, letterSpacing: -0.75 },
    title: { fontSize: 26, lineHeight: 40, letterSpacing: -0.85 },
    body: { fontSize: 16, lineHeight: 22.75 },
    bodySm: { fontSize: 14, lineHeight: 20 },
    caption: { fontSize: 12, lineHeight: 16 },
    button: { fontSize: 14, lineHeight: 20, letterSpacing: -0.14 },
  },
  shadow: {
    card: {
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    button: {
      shadowColor: "#1e3a8a",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 10,
      elevation: 4,
    },
    logo: {
      shadowColor: "#1e3a8a",
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.25,
      shadowRadius: 20,
      elevation: 8,
    },
  },
} as const;
