/*
 * SPDX-FileCopyrightText: 2026 Karsaaz
 * SPDX-License-Identifier: AGPL-3.0-or-later
 */

export const theme = {
  colors: {
    background: "#fafafa",
    surface: "#ffffff",
    surfaceMuted: "#fafafa",
    text: "#09090b",
    textDark: "#09090b",
    textSecondary: "#555555",
    textMuted: "#71717b",
    textSubtle: "#919194",
    border: "#dfe1e4",
    borderLight: "#e4e4e7",
    inputBg: "#fafafa",
    infoBg: "rgba(164,179,255,0.5)",
    accent: "#4e3cf4",
    accentBright: "#2b7fff",
    accentText: "#4b66ff",
    link: "#1d84f5",
    success: "#28bc5e",
    successBright: "#34d399",
    gradientStart: "#5d7cf6",
    gradientEnd: "#4e3cf4",
    tabBar: "#1d1f2b",
    tabBarActive: "#ffffff",
    tabBarInactive: "#ffffff",
    drawerHeaderStart: "#5d7cf6",
    drawerHeaderEnd: "#4e3cf4",
    storageImages: "#10b981",
    storageDocs: "#3b82f6",
    storageVideos: "#f59e0b",
    storageOther: "#d946ef",
    storageEmpty: "#cbd5e1",
    folderOrangeStart: "#f59e0b",
    folderOrangeEnd: "#ea580c",
  },
  radius: {
    sm: 6,
    md: 12,
    lg: 16,
    xl: 24,
    pill: 999,
  },
  spacing: {
    screen: 24,
    card: 16,
    gap: 8,
  },
  typography: {
    hero: { fontSize: 30, lineHeight: 36, letterSpacing: -0.75 },
    title: { fontSize: 26, lineHeight: 40, letterSpacing: -0.85 },
    body: { fontSize: 16, lineHeight: 22.75 },
    bodySm: { fontSize: 14, lineHeight: 20 },
    caption: { fontSize: 12, lineHeight: 16 },
    button: { fontSize: 14, lineHeight: 20, letterSpacing: -0.14 },
  },
  shadow: {
    card: {
      shadowColor: "#0f172a",
      shadowOffset: { width: 0, height: 2 },
      shadowOpacity: 0.06,
      shadowRadius: 6,
      elevation: 2,
    },
    button: {
      shadowColor: "#1e3a8a",
      shadowOffset: { width: 0, height: 4 },
      shadowOpacity: 0.15,
      shadowRadius: 10,
      elevation: 4,
    },
    logo: {
      shadowColor: "#1e3a8a",
      shadowOffset: { width: 0, height: 16 },
      shadowOpacity: 0.25,
      shadowRadius: 20,
      elevation: 8,
    },
  },
} as const;
